#!/bin/bash

set -eo pipefail

main()
{
  declare action="${1}"
  declare ip="${2}"
  find "/etc/fail2ban-action.d" -type "f" -executable -print0 |
    sort --zero-terminated |
    xargs --null --no-run-if-empty --replace={} /bin/sh -c '"${0}" "${1}" "${2}"' "{}" "${action}" "${ip}"
}

main "${@}"
