---
- name: copy time file
  template:
    src: "etc_systemd_system_timer-name.timer.j2"
    dest: "/etc/systemd/system/{{ systemd_timer_name }}.timer"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o="

- name: reload systemd
  systemd:
    daemon_reload: yes
