---
- name: install fail2ban's APT package
  apt:
    name: "fail2ban"
    state: present
    update_cache: yes

- name: configure fail2ban filter for port scan
  copy:
    content: |
      [Definition]
      failregex = UFW BLOCK.* SRC=<HOST>
      ignoreregex =
    dest: "/etc/fail2ban/filter.d/port-scan.conf"
    owner: "root"
    mode: "u=rw,g=r,o="
  notify: restart fail2ban

- name: configure fail2ban jail for port scan
  copy:
    content: |
      [port-scan]
      bantime = 60
      enabled = true
      filter = port-scan
      logpath = /var/log/ufw.log
      action = ufw
      maxretry = 5
    dest: "/etc/fail2ban/jail.d/port-scan.conf"
    owner: "root"
    mode: "u=rw,g=r,o="
  notify: restart fail2ban
