---
- name: copy service file
  template:
    src: "etc_systemd_system_service-name.service.j2"
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o="

- name: reload systemd
  systemd:
    name: "{{ systemd_service_name }}.service"
    daemon_reload: yes
