---
- name: configure fail2ban filter
  copy:
    content: |
      [Definition]
      failregex = UFW BLOCK.* SRC=<HOST>
      ignoreregex =
    dest: "/etc/fail2ban/filter.d/ufw.local"
    owner: "root"
    mode: "u=rw,g=r,o="
  notify: restart fail2ban

- name: configure fail2ban jail
  copy:
    content: |
      [ufw]
      enabled = true
      filter = ufw
      logpath = /var/log/ufw.log
      action = %(action_)s[cause=%(__name__)s]
    dest: "/etc/fail2ban/jail.d/ufw.local"
    owner: "root"
    mode: "u=rw,g=r,o="
  notify: restart fail2ban
